### ISSUE TITLE
Only works if refresh not 1

### ISSUE THREAD

**Issue by JonnyTech** [mcastillof/FakeTraveler#15]
With location refesh count set to 1 (the default) the mock location is not updated. Setting to 100 or 0 works.

Also, the `apply` button does not change to `stop` once started.

**Comment by mcastillof** [comment]
@JonnyTech, can you confirm that you still have this problem? 
You are using version 1.6, right? you will have to see the version in F-droid as it is not shown within the app.

Remember that when the refresh count is 1 and you tap the Apply button, the location is mocked instantly. So you can't go to another app to see if the location was changed.

When I want to do some test I always split the screen in two. I use Fake Traveler and OSMand+. By doing this, refresh count 1 is working for me.

**Comment by JonnyTech** [comment]
Ah, I see. Yes, `FakeTraveler` does send location information a single time. I wrongly assumed that the Android system would somehow cache that value and present it to other apps. Thanks for the feedback. Sorry for the noise.
