### ISSUE TITLE
After closing the app, it's suddenly crashed

### ISSUE THREAD

**Issue by dikiaap** [mcastillof/FakeTraveler#16]
I'm on Android 6 and use Play Service. After pressing apply button, close the app, and it's suddenly crashed.

The status of fake traveler service is still active, but the button is become apply button again, not stop button.

**Comment by mcastillof** [comment]
Hello @dikiaap, can you provide a logcat of the crash, please  :)

**Comment by dikiaap** [comment]
Nice. Thank you
