### ISSUE TITLE
Request: move on change

### ISSUE THREAD

**Issue by JonnyTech** [mcastillof/FakeTraveler#3]
If i want to change my location, the current process is to long press a new place then stop and reapply the service. Is it possible to move just by long pressing - provided that the service has already been started and is not stopped?

**Comment by mcastillof** [comment]
That sounds fine to me. I don't have the time to do it right now, but maybe I can change the code in the weekend. You can also feel free to make the change and pull a request.

**Comment by JonnyTech** [comment]
If you give me a pointer where to start then I shall give it a go, but I am not an Android developer and may need tips in setting up a development environment. But I am up for the challenge in a few days when I get back home.

**Comment by mcastillof** [comment]
Hello, JonnyTech. I have done the code. I have changed a bit how the app internally works, so I'm running some test, before doing the release. 

About setting up a development enviroment is not hard at all if you use Android Studio IDE (I guess is not FLOSS). I found an alternative, but I haven't tested. It is not an IDE. https://wiki.debian.org/AndroidTools/IntroBuildingApps

**Comment by JonnyTech** [comment]
Thanks for both implementing the code and the tutorial - shall put that on my todo list, as I do run Debian, but debugging looks nonexistent!

**Comment by mcastillof** [comment]
@JonnyTech, I have released version 1.5 with this enhancement. It should be released in F-Droid in a few days. Please create a new issue in case of bugs.
