### ISSUE TITLE
Map is blank

### ISSUE THREAD

**Issue by tguen** [mcastillof/FakeTraveler#37]
When I open the app, it shows the title bar, coordinates, zoom buttons and copyright info, but no map.

![Screenshot_20210120-234555](https://user-images.githubusercontent.com/57420975/105319693-13b99800-5b7a-11eb-8bf0-5d628a826907.png)

Pixel 4a/Android 11, Nokia 6.1/Android 10
git master 2021-01-20 (6602b380d9a380608b4f59d3c2aeebd7b8458141)

**Comment by tatusamma** [comment]
Can confirm. Removed all data, deleted cache, reinstalled and problem persists.

**Comment by romeovidaselect** [comment]
Hello, @tatusamma , im having the same issue. I already tried remove all data and delete cache and reinstall the problem still persist.

**Comment by ef1x** [comment]
Hi, 

seems like mapbox deprecated the API that's used: https://blog.mapbox.com/deprecating-studio-classic-styles-d8892ac38cb4?gi=a06793ca0cf9 

There is a migration manual: https://docs.mapbox.com/help/troubleshooting/migrate-legacy-static-tiles-api/?/=blog&utm_source=mapbox-blog&utm_campaign=blog%7Cmapbox-blog%7Cdoc-migrate-static%7Cdeprecating-studio-classic-styles-d8892ac38cb4-20-03&utm_term=doc-migrate-static&utm_content=deprecating-studio-classic-styles-d8892ac38cb4

I gave it a try and it worked out fine. Will create a pull request

**Comment by mdelem** [comment]
Thanks @ef1x, I tested your change on my phone (Android 7.1.2) and it solves the issue.

**Comment by mcastillof** [comment]
Sorry, I have been very busy. It was merged. thanks :)
