### ISSUE TITLE
Map blank 

### ISSUE THREAD

**Issue by jxmesth** [mcastillof/FakeTraveler#57]
When opening the application, all that is visible is a blank grey screen and no map is visible. The last time this happened was when mapbox changed its API. 

Can someone please take a look at this? Just making sure if I'm the only one experiencing this.

**Comment by letsgonyc** [comment]
Same issue here.

**Comment by wegma** [comment]
I too have this same issue

**Comment by jxmesth** [comment]
Looks like we definitely need a fix

**Comment by mcastillof** [comment]
I have applied a fix. A new version should arrive to F-Droid soon, hopefully automatically. If after a few days it is not, please reopen this issue. I'm closing it now.

**Comment by jxmesth** [comment]
@mcastillof thank you so much for your quick reply and action on this :)

**Comment by comminutus** [comment]
I have the same issue but the version on F-Droid says it was updated nearly two years ago.  Am I missing something?

**Comment by mcastillof** [comment]
We have  a problem with the building in F-droid. See #59 and please comment if you know how to deal with it.
