### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [mcastillof/FakeTraveler#59]
IIRC, this **was** in the past an error we could ignore via lint options: https://gitlab.com/fdroid/fdroiddata/-/jobs/4012666000#L630 but not any more?

**Comment by mcastillof** [comment]
Hi @licaon-kter. To be honest, I don't know what caused the problem, nor how to solve it. I did this change on the hope that it works. I also updated the tag and release version. https://github.com/mcastillof/FakeTraveler/commit/5e443dbd3408ffbf65e1fa1642873e94cc8bfade

**Comment by licaon-kter** [comment]
I guess the text should be self explanatory.

What's odd is, you don't see the same error? You build in Android Studio or command line?

**Comment by mcastillof** [comment]
@licaon-kter, thanks for helping me to fix this. https://gitlab.com/fdroid/fdroiddata/-/merge_requests/12850
