### ISSUE TITLE
translation pt-br

### ISSUE THREAD

**Issue by hanelore** [mcastillof/FakeTraveler#6]
Hi.

What would be the best way to start the translation?

Thanks.

**Comment by mcastillof** [comment]
Hello hanelore, this weekend I will put all strings in strings.xml file. I will provide more info then.

**Comment by hanelore** [comment]
Thanks @mcastillof I will wait so.

Can I close this issue?

**Comment by mcastillof** [comment]
Hello hanelore, I have pushed the commit fea4de78890f2658a69fc3d6fe5150238008857c to allow easy translations. English translation may have some mistakes as is not my first language. Spanish version (also pushed in the same commit) might be better.

**Comment by hanelore** [comment]
Thanks again @mcastillof I will write the pt-br version and review the English version too open in [issue 8](https://github.com/mcastillof/FakeTraveler/issues/8).
